definitions:
  steps:
    - step: &deploy
        name: Deploy
        script:
          - pipe: atlassian/trigger-pipeline:5.0.0
            variables:
              BITBUCKET_USERNAME: "$DEPLOY_TO_CLOUD_USER"
              BITBUCKET_APP_PASSWORD: "$DEPLOY_TO_CLOUD_PASS"
              REPOSITORY: "$BITBUCKET_REPO_SLUG"
              REF_TYPE: 'branch'
              REF_NAME: 'deploy-to-cloud'
              CUSTOM_PIPELINE_NAME: "$BITBUCKET_BRANCH"
              DEBUG: 'true'
    - step: &pr
        name: Pull Request Checks
        script:
          - pipe: atlassian/trigger-pipeline:5.0.0
            variables:
              BITBUCKET_USERNAME: "$DEPLOY_TO_CLOUD_USER"
              BITBUCKET_APP_PASSWORD: "$DEPLOY_TO_CLOUD_PASS"
              REPOSITORY: "$BITBUCKET_REPO_SLUG"
              REF_TYPE: 'branch'
              REF_NAME: 'deploy-to-cloud'
              CUSTOM_PIPELINE_NAME: 'pull-request'
              PIPELINE_VARIABLES: >
                  [{
                    "key": "DEPLOY_BRANCH",
                    "value": "$BITBUCKET_BRANCH"
                  }]
              DEBUG: 'true'
              WAIT: 'true'
pipelines:
  pull-requests:
    "**":
      - step: *pr
  branches:
    development:
      - step: *deploy
    staging:
      - step: *deploy
    master:
      - step: *deploy